//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace BLD_Master.Properties {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("BLD_Master.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   重写当前线程的 CurrentUICulture 属性
        ///   重写当前线程的 CurrentUICulture 属性。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 数量	概率
        ///0	1.134046e-08
        ///0.5	2.381497e-07
        ///1	6.191891e-06
        ///1.5	9.311652e-05
        ///2	0.001143357
        ///2.5	0.01063910
        ///3	0.06899270
        ///3.5	0.2626665
        ///4	0.3821147
        ///4.5	0.2248650
        ///5	0.04774306
        ///5.5	0.001736111
        ///均值	3.9439561695734535
        ///标准差	0.2685361526720538 的本地化字符串。
        /// </summary>
        internal static string CornerStatistics {
            get {
                return ResourceManager.GetString("CornerStatistics", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 数量	概率
        ///0	2.312032e-20
        ///1	3.500416e-17
        ///2	2.098640e-14
        ///3	7.221221e-12
        ///4	1.606755e-09
        ///5	2.335786e-07
        ///6	2.114250e-05
        ///7	0.001085375
        ///8	0.0267720
        ///9	0.2362029
        ///10	0.5017181
        ///11	0.2170380
        ///12	0.0170080
        ///13	0.0001540588
        ///14	3.767602e-08
        ///均值	9.958427493364441
        ///标准差	0.6381326746376601 的本地化字符串。
        /// </summary>
        internal static string CubeStatistics {
            get {
                return ResourceManager.GetString("CubeStatistics", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 数量	概率
        ///0	1.019373e-12
        ///0.5	2.242620e-11
        ///1	5.158027e-10
        ///1.5	9.531137e-09
        ///2	1.565910e-07
        ///2.5	2.256525e-06
        ///3	2.799261e-05
        ///3.5	0.0002919788
        ///4	0.002476726
        ///4.5	0.01626882
        ///5	0.07662396
        ///5.5	0.2266443
        ///6	0.3310823
        ///6.5	0.2413949
        ///7	0.08878605
        ///7.5	0.01538694
        ///8	0.001002785
        ///8.5	1.085069e-05
        ///均值	6.014471323790986
        ///标准差	0.3695288410565709 的本地化字符串。
        /// </summary>
        internal static string EdgeStatistics {
            get {
                return ResourceManager.GetString("EdgeStatistics", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 作者：鲁曦（2018LUXI01）
        ///更新日期：2019.12.3 的本地化字符串。
        /// </summary>
        internal static string String1 {
            get {
                return ResourceManager.GetString("String1", resourceCulture);
            }
        }
    }
}
